const data = {
    products: [
      {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'None',
        rating: 4.5,
        numReviews: 10,
        description: 'Nice product',
      },
      {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 100,
        brand: 'None',
        rating: 4.0,
        numReviews: 10,
        description: 'Nice product',
      },
      {
        _id: '3',
        name: 'Free-size Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 220,
        brand: 'none',
        rating: 4.8,
        numReviews: 17,
        description: 'Nice product',
      },
      {
        _id: '4',
        name: 'Slim Pant',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 78,
        brand: 'None',
        rating: 4.5,
        numReviews: 14,
        description: 'Nice product',
      },
      {
        _id: '5',
        name: 'Slim-fit Pant',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 65,
        brand: 'none',
        rating: 4.5,
        numReviews: 10,
        description: 'Nice product',
      },
      {
        _id: '6',
        name: 'Fit Pant',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 139,
        brand: 'none',
        rating: 4.5,
        numReviews: 15,
        description: 'Nice product',
      },
    ],
  };
  export default data;
  